[FIX] partner_tier_validation: Allow to open view_partner_simple_form
Caused by: EvalError: Can not evaluate python expression: (bool(bool(review_ids)))
    Error: Name 'review_ids' is not defined
    EvalError: Can not evaluate python expression: (bool(bool(review_ids)))
    Error: Name 'review_ids' is not defined