[IMP] partner_rank_single: less invasive constraint on rank increase
Instead of running the constraint check on `_increase_rank`, we now avoid
increasing it if the partner is already ranked in the opposite field.

This fixes an error that occurs when installing demo data of core modules:

```python-traceback
2025-12-11 11:44:05,845 35 ERROR testdb odoo.addons.account.demo.account_demo: Error while posting demo data
Traceback (most recent call last):
  File ".../odoo/addons/account/demo/account_demo.py", line 90, in _post_load_demo_data
    move.action_post()
  File ".../odoo/addons/account/models/account_move.py", line 5426, in action_post
    self._post(soft=False)
  File ".../odoo/addons/account/models/account_move.py", line 5154, in _post
    (partner | partner.commercial_partner_id)._increase_rank('supplier_rank', count)
  File ".../partner-contact/partner_rank_single/models/res_partner.py", line 23, in _increase_rank
    "supplier_rank": "customer_rank",
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../partner-contact/partner_rank_single/models/res_partner.py", line 15, in _constrains_single_rank
    raise ValidationError(
odoo.exceptions.ValidationError: A contact cannot be both a customer and a supplier.
```