[FIX] partner_financial_risk: Allow contact creation
Without this patch, when creating a new contact from the partner form, users got this traceback:

```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/opt/odoo/custom/src/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/auto/addons/partner_financial_risk/models/res_partner.py", line 119, in _compute_risk_invoice
    active_test=False).search([('id', 'child_of', partner.id)]).ids
  File "/opt/odoo/custom/src/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/openerp/api.py", line 490, in new_api
    result = method(self._model, cr, uid, *args, **old_kwargs)
  File "/opt/odoo/custom/src/odoo/openerp/models.py", line 1668, in search
    return self._search(cr, user, args, offset=offset, limit=limit, order=order, context=context, count=count)
  File "/opt/odoo/custom/src/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/openerp/addons/base/res/res_partner.py", line 626, in _search
    count=count, access_rights_uid=access_rights_uid)
  File "/opt/odoo/custom/src/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/openerp/models.py", line 4793, in _search
    query = self._where_calc(cr, user, args, context=context)
  File "/opt/odoo/custom/src/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/openerp/models.py", line 4564, in _where_calc
    e = expression.expression(cr, user, domain, self, context)
  File "/opt/odoo/custom/src/odoo/openerp/osv/expression.py", line 644, in __init__
    self.parse(cr, uid, context=context)
  File "/opt/odoo/custom/src/odoo/openerp/osv/expression.py", line 834, in parse
    ids2 = to_ids(right, model, context)
  File "/opt/odoo/custom/src/odoo/openerp/osv/expression.py", line 708, in to_ids
    return list(value)
TypeError: 'NewId' object is not iterable
```

Patch includes a recomputation when the partner is or not set as customer, since the field is used in the method.